[package]
name = "aio-plugin-settings"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
az-dioxus-admin-shell = { git = "https://github.com/zjarlin/dioxus-admin-workbench.git", rev = "bc77f06cf705873e9aeb17bd260a5ec98184e84d" }
az-ui-components = { git = "https://github.com/zjarlin/dioxus-admin-workbench.git", rev = "bc77f06cf705873e9aeb17bd260a5ec98184e84d" }
dill = "0.15.0"
dioxus = { version = "=0.7.9", default-features = false, features = ["macro", "html", "signals"] }

[lints.rust]
unsafe_code = "forbid"
